/*
 * generated by Xtext 2.39.0
 */
package com.example.xai.ide;

import com.example.xai.XAIModelRuntimeModule;
import com.example.xai.XAIModelStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class XAIModelIdeSetup extends XAIModelStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new XAIModelRuntimeModule(), new XAIModelIdeModule()));
	}
	
}
