/*
 * generated by Xtext 2.39.0
 */
package com.example.xai.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractXAIModelScopeProvider extends DelegatingScopeProvider {
}
