/*
 * generated by Xtext 2.39.0
 */
package com.example.xai.serializer;

import com.example.xai.model.explainableAI.Dataset;
import com.example.xai.model.explainableAI.Model;
import com.example.xai.model.explainableAI.User;
import com.example.xai.model.explainableAI.explainableAIPackage;
import com.example.xai.services.XAIModelGrammarAccess;
import com.example.xai.xAIModel.Root;
import com.example.xai.xAIModel.XAIModelPackage;
import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class XAIModelSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private XAIModelGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == explainableAIPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case explainableAIPackage.DATASET:
				sequence_DatasetSpec(context, (Dataset) semanticObject); 
				return; 
			case explainableAIPackage.MODEL:
				sequence_ModelSpec(context, (Model) semanticObject); 
				return; 
			case explainableAIPackage.USER:
				sequence_UserSpec(context, (User) semanticObject); 
				return; 
			}
		else if (epackage == XAIModelPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case XAIModelPackage.ROOT:
				sequence_Root(context, (Root) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     DatasetSpec returns Dataset
	 *
	 * Constraint:
	 *     (path=STRING format=ID targetColumn=STRING?)
	 * </pre>
	 */
	protected void sequence_DatasetSpec(ISerializationContext context, Dataset semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ModelSpec returns Model
	 *
	 * Constraint:
	 *     (name=ID modelType=ID user=UserSpec dataset=DatasetSpec method=ID?)
	 * </pre>
	 */
	protected void sequence_ModelSpec(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Root returns Root
	 *
	 * Constraint:
	 *     model=ModelSpec
	 * </pre>
	 */
	protected void sequence_Root(ISerializationContext context, Root semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, XAIModelPackage.Literals.ROOT__MODEL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XAIModelPackage.Literals.ROOT__MODEL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRootAccess().getModelModelSpecParserRuleCall_0(), semanticObject.getModel());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     UserSpec returns User
	 *
	 * Constraint:
	 *     (name=ID expertise=ID (format+=ID format+=ID*)? details=ID? purpose=ID?)
	 * </pre>
	 */
	protected void sequence_UserSpec(ISerializationContext context, User semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
