/*
 * generated by Xtext 2.39.0
 */
package com.example.xai.validation;

import java.util.LinkedHashSet;
import java.util.Set;

import org.eclipse.xtext.validation.Check;

import com.example.xai.generator.ConfigurationCache;
import com.example.xai.model.explainableAI.Dataset;
import com.example.xai.model.explainableAI.Model;
import com.example.xai.model.explainableAI.User;
import com.example.xai.model.explainableAI.explainableAIPackage;
import com.example.xai.model.xaiConfig.AIModel;
import com.example.xai.model.xaiConfig.Configuration;
import com.example.xai.model.xaiConfig.ExplanationMethod;

import com.example.xai.verification.Z3VerificationResult;
import com.example.xai.verification.Z3VerificationService;
import java.util.List;


public class XAIModelValidator extends AbstractXAIModelValidator {

    @Check
    public void checkUserAgainstRepository(User user) {
        Configuration config = ConfigurationCache.get(user.eResource());
        if (config == null) {
            return;
        }

        if (user.getExpertise() != null && !user.getExpertise().trim().isEmpty()
                && ConfigurationCache.findExpertise(config, user.getExpertise()) == null) {
            error("Unknown expertise level '" + user.getExpertise() + "'. It is not defined in config.xmi.",
                    user, explainableAIPackage.Literals.USER__EXPERTISE);
        }

        if (user.getDetails() != null && !user.getDetails().trim().isEmpty()
                && ConfigurationCache.findDetails(config, user.getDetails()) == null) {
            error("Unknown details level '" + user.getDetails() + "'. It is not defined in config.xmi.",
                    user, explainableAIPackage.Literals.USER__DETAILS);
        }

        if (user.getPurpose() != null && !user.getPurpose().trim().isEmpty()
                && ConfigurationCache.findPurpose(config, user.getPurpose()) == null) {
            error("Unknown purpose '" + user.getPurpose() + "'. It is not defined in config.xmi.",
                    user, explainableAIPackage.Literals.USER__PURPOSE);
        }

        Set<String> seenFormats = new LinkedHashSet<>();
        for (String rawFormat : user.getFormat()) {
            if (rawFormat == null || rawFormat.trim().isEmpty()) {
                continue;
            }
            String fmt = rawFormat.trim();
            if (!seenFormats.add(fmt.toLowerCase())) {
                error("Duplicate output format '" + rawFormat + "'.", user,
                        explainableAIPackage.Literals.USER__FORMAT);
            }
            if (ConfigurationCache.findOutputFormat(config, fmt) == null) {
                error("Unknown output format '" + rawFormat + "'. It is not defined in config.xmi.",
                        user, explainableAIPackage.Literals.USER__FORMAT);
            }
        }
    }

    @Check
    public void checkModelAndRepositoryConsistency(Model model) {
        Configuration config = ConfigurationCache.get(model.eResource());
        if (config == null) {
            warning("Configuration repository could not be loaded; repository-based validation was skipped.", model,
                    explainableAIPackage.Literals.MODEL__MODEL_TYPE);
            return;
        }

        AIModel modelEntry = ConfigurationCache.findModel(config, model.getModelType());
        if (modelEntry == null) {
            error("Unknown AI model type '" + model.getModelType() + "'. It is not defined in config.xmi.", model,
                    explainableAIPackage.Literals.MODEL__MODEL_TYPE);
            return;
        }

        Dataset dataset = model.getDataset();
        if (dataset != null) {
            String datasetType = dataset.getFormat();
            if (datasetType == null || datasetType.trim().isEmpty()) {
                error("A dataset type is required.", dataset,
                        explainableAIPackage.Literals.DATASET__FORMAT);
            } else {
                if (ConfigurationCache.findDatasetType(config, datasetType) == null) {
                    error("Unknown dataset type '" + datasetType + "'. It is not defined in config.xmi.", dataset,
                            explainableAIPackage.Literals.DATASET__FORMAT);
                } else {
                    if (!ConfigurationCache.modelSupportsDatasetType(modelEntry, datasetType)) {
                        error("Dataset type '" + datasetType + "' is not listed as supported by AI model '"
                                + modelEntry.getName() + "'.",
                                dataset, explainableAIPackage.Literals.DATASET__FORMAT);
                    }

                    boolean targetRequired = ConfigurationCache.datasetTypeRequiresTargetColumn(config, datasetType);
                    boolean targetProvided = dataset.getTargetColumn() != null && !dataset.getTargetColumn().trim().isEmpty();

                    if (targetRequired && !targetProvided) {
                        error("Dataset type '" + datasetType + "' requires a target column.",
                                dataset, explainableAIPackage.Literals.DATASET__TARGET_COLUMN);
                    } else if (!targetRequired && targetProvided) {
                        warning("Dataset type '" + datasetType + "' does not require a target column; the provided value will be ignored.",
                                dataset, explainableAIPackage.Literals.DATASET__TARGET_COLUMN);
                    }
                }
            }
        }

        if (model.getMethod() != null && !model.getMethod().trim().isEmpty()) {
            ExplanationMethod methodEntry = ConfigurationCache.findMethod(config, model.getMethod());
            if (methodEntry == null) {
                error("Unknown explanation method '" + model.getMethod() + "'. It is not defined in config.xmi.",
                        model, explainableAIPackage.Literals.MODEL__METHOD);
                return;
            }

            if (!modelEntry.getAllowedMethods().contains(methodEntry)) {
                warning("Explanation method '" + methodEntry.getName()
                        + "' is defined in the repository but is not listed as compatible with model type '"
                        + modelEntry.getName() + "'.",
                        model, explainableAIPackage.Literals.MODEL__METHOD);
            }

            if (!ConfigurationCache.supportsAllFormats(methodEntry, model.getUser().getFormat())) {
                error("One or more requested output formats are not supported by explanation method '"
                        + methodEntry.getName() + "'.",
                        model.getUser(), explainableAIPackage.Literals.USER__FORMAT);
            }

            if (ConfigurationCache.expertiseRank(config, model.getUser().getExpertise()) != -1
                    && ConfigurationCache.expertiseRank(methodEntry.getMinExpertise()) != -1
                    && ConfigurationCache.expertiseRank(config, model.getUser().getExpertise())
                            < ConfigurationCache.expertiseRank(methodEntry.getMinExpertise())) {
                warning("User expertise '" + model.getUser().getExpertise()
                        + "' is lower than the minimum expertise required by method '"
                        + methodEntry.getName() + "' (" + methodEntry.getMinExpertise().getName() + ").",
                        model, explainableAIPackage.Literals.MODEL__METHOD);
            }

            String effectivePurpose = (model.getUser().getPurpose() == null || model.getUser().getPurpose().trim().isEmpty())
                    ? ConfigurationCache.defaultPurposeName(config)
                    : model.getUser().getPurpose().trim();

            if (!ConfigurationCache.isRecommendedPurpose(methodEntry, effectivePurpose)) {
                warning("Purpose '" + effectivePurpose + "' is not listed as a recommended purpose for method '"
                        + methodEntry.getName() + "'.",
                        model.getUser(), explainableAIPackage.Literals.USER__PURPOSE);
            }

            if ("debugging".equalsIgnoreCase(effectivePurpose) && !ConfigurationCache.hasDebugTechniques(methodEntry)) {
                warning("Purpose 'debugging' was requested, but method '" + methodEntry.getName()
                        + "' has no debug techniques declared in the configuration repository.",
                        model.getUser(), explainableAIPackage.Literals.USER__PURPOSE);
            }
        }
    }
    
    /**
     * Z3-backed verification of repository properties P1, P2, P3.
     * Reports an ERROR if any property is violated (unusual — indicates 
     * config.xmi has been edited into an inconsistent state).
     */
    @Check
    public void checkRepositoryWithZ3(com.example.xai.xAIModel.Root root) {
        Configuration config = ConfigurationCache.get(root.eResource());
        if (config == null) return;

        List<Z3VerificationResult> results =
            Z3VerificationService.verifyRepository(config);

        for (Z3VerificationResult r : results) {
            if (r.isViolated()) {
                error(
                    "[Z3-" + r.getProperty() + "] " + r.getMessage() +
                    (r.getCounterexample() != null
                        ? "  Counterexample: " + r.getCounterexample() : ""),
                    root,
                    com.example.xai.xAIModel.XAIModelPackage.Literals.ROOT__MODEL);
            }
            // PROVED and SKIPPED are silent
        }
    }

    /**
     * Z3-backed verification of a single user specification.
     * Checks that the declared (modelType, expertise, format) combination
     * will yield a compatible explanation method at generation time.
     *
     * Reports an ERROR if the combination is provably incompatible,
     * or an INFO note if Z3 confirms it is always solvable.
     */
    @Check
    public void checkSpecificationWithZ3(
            com.example.xai.model.explainableAI.Model model) {
        Configuration config = ConfigurationCache.get(model.eResource());
        if (config == null) return;

        Z3VerificationResult result =
            Z3VerificationService.verifySpecification(model, config);

        if (result.isViolated()) {
            error(
                "[Z3-SPEC] " + result.getMessage() +
                (result.getCounterexample() != null
                    ? "  Suggestion: " + result.getCounterexample() : ""),
                model,
                com.example.xai.model.explainableAI.explainableAIPackage
                    .Literals.MODEL__MODEL_TYPE);
        }
        // PROVED and SKIPPED produce no marker
    }

}