/*
 * generated by Xtext 2.39.0
 */
package com.example.xai.ide.contentassist.antlr;

import com.example.xai.ide.contentassist.antlr.internal.InternalXAIModelParser;
import com.example.xai.services.XAIModelGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class XAIModelParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(XAIModelGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, XAIModelGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getModelSpecAccess().getGroup(), "rule__ModelSpec__Group__0");
			builder.put(grammarAccess.getModelSpecAccess().getGroup_8(), "rule__ModelSpec__Group_8__0");
			builder.put(grammarAccess.getUserSpecAccess().getGroup(), "rule__UserSpec__Group__0");
			builder.put(grammarAccess.getUserSpecAccess().getGroup_5(), "rule__UserSpec__Group_5__0");
			builder.put(grammarAccess.getUserSpecAccess().getGroup_5_4(), "rule__UserSpec__Group_5_4__0");
			builder.put(grammarAccess.getUserSpecAccess().getGroup_6(), "rule__UserSpec__Group_6__0");
			builder.put(grammarAccess.getUserSpecAccess().getGroup_7(), "rule__UserSpec__Group_7__0");
			builder.put(grammarAccess.getDatasetSpecAccess().getGroup(), "rule__DatasetSpec__Group__0");
			builder.put(grammarAccess.getDatasetSpecAccess().getGroup_7(), "rule__DatasetSpec__Group_7__0");
			builder.put(grammarAccess.getRootAccess().getModelAssignment(), "rule__Root__ModelAssignment");
			builder.put(grammarAccess.getModelSpecAccess().getNameAssignment_1(), "rule__ModelSpec__NameAssignment_1");
			builder.put(grammarAccess.getModelSpecAccess().getModelTypeAssignment_3(), "rule__ModelSpec__ModelTypeAssignment_3");
			builder.put(grammarAccess.getModelSpecAccess().getUserAssignment_5(), "rule__ModelSpec__UserAssignment_5");
			builder.put(grammarAccess.getModelSpecAccess().getDatasetAssignment_7(), "rule__ModelSpec__DatasetAssignment_7");
			builder.put(grammarAccess.getModelSpecAccess().getMethodAssignment_8_1(), "rule__ModelSpec__MethodAssignment_8_1");
			builder.put(grammarAccess.getUserSpecAccess().getNameAssignment_1(), "rule__UserSpec__NameAssignment_1");
			builder.put(grammarAccess.getUserSpecAccess().getExpertiseAssignment_4(), "rule__UserSpec__ExpertiseAssignment_4");
			builder.put(grammarAccess.getUserSpecAccess().getFormatAssignment_5_3(), "rule__UserSpec__FormatAssignment_5_3");
			builder.put(grammarAccess.getUserSpecAccess().getFormatAssignment_5_4_1(), "rule__UserSpec__FormatAssignment_5_4_1");
			builder.put(grammarAccess.getUserSpecAccess().getDetailsAssignment_6_2(), "rule__UserSpec__DetailsAssignment_6_2");
			builder.put(grammarAccess.getUserSpecAccess().getPurposeAssignment_7_2(), "rule__UserSpec__PurposeAssignment_7_2");
			builder.put(grammarAccess.getDatasetSpecAccess().getPathAssignment_3(), "rule__DatasetSpec__PathAssignment_3");
			builder.put(grammarAccess.getDatasetSpecAccess().getFormatAssignment_6(), "rule__DatasetSpec__FormatAssignment_6");
			builder.put(grammarAccess.getDatasetSpecAccess().getTargetColumnAssignment_7_2(), "rule__DatasetSpec__TargetColumnAssignment_7_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private XAIModelGrammarAccess grammarAccess;

	@Override
	protected InternalXAIModelParser createParser() {
		InternalXAIModelParser result = new InternalXAIModelParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public XAIModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XAIModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
