/**
 * generated by Xtext 2.39.0
 */
package com.example.xai.xAIModel;

import com.example.xai.model.explainableAI.Model;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Root</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.example.xai.xAIModel.Root#getModel <em>Model</em>}</li>
 * </ul>
 *
 * @see com.example.xai.xAIModel.XAIModelPackage#getRoot()
 * @model
 * @generated
 */
public interface Root extends EObject
{
  /**
	 * Returns the value of the '<em><b>Model</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Model</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Model</em>' containment reference.
	 * @see #setModel(Model)
	 * @see com.example.xai.xAIModel.XAIModelPackage#getRoot_Model()
	 * @model containment="true"
	 * @generated
	 */
  Model getModel();

  /**
	 * Sets the value of the '{@link com.example.xai.xAIModel.Root#getModel <em>Model</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Model</em>' containment reference.
	 * @see #getModel()
	 * @generated
	 */
  void setModel(Model value);

} // Root
