/**
 * generated by Xtext 2.39.0
 */
package com.example.xai.xAIModel;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.example.xai.xAIModel.XAIModelFactory
 * @model kind="package"
 * @generated
 */
public interface XAIModelPackage extends EPackage
{
  /**
	 * The package name.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNAME = "xAIModel";

  /**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNS_URI = "http://www.example.org/xai/DSL";

  /**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNS_PREFIX = "xAIModel";

  /**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  XAIModelPackage eINSTANCE = com.example.xai.xAIModel.impl.XAIModelPackageImpl.init();



  /**
	 * The meta object id for the '{@link com.example.xai.xAIModel.impl.RootImpl <em>Root</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see com.example.xai.xAIModel.impl.RootImpl
	 * @see com.example.xai.xAIModel.impl.XAIModelPackageImpl#getRoot()
	 * @generated
	 */
	int ROOT = 0;

		/**
	 * The feature id for the '<em><b>Model</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ROOT__MODEL = 0;

		/**
	 * The number of structural features of the '<em>Root</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ROOT_FEATURE_COUNT = 1;



		/**
	 * Returns the meta object for class '{@link com.example.xai.xAIModel.Root <em>Root</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Root</em>'.
	 * @see com.example.xai.xAIModel.Root
	 * @generated
	 */
  EClass getRoot();

  /**
	 * Returns the meta object for the containment reference '{@link com.example.xai.xAIModel.Root#getModel <em>Model</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Model</em>'.
	 * @see com.example.xai.xAIModel.Root#getModel()
	 * @see #getRoot()
	 * @generated
	 */
  EReference getRoot_Model();

  /**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
  XAIModelFactory getXAIModelFactory();

  /**
	 * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
	 * @generated
	 */
  interface Literals
  {
    /**
		 * The meta object literal for the '{@link com.example.xai.xAIModel.impl.RootImpl <em>Root</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see com.example.xai.xAIModel.impl.RootImpl
		 * @see com.example.xai.xAIModel.impl.XAIModelPackageImpl#getRoot()
		 * @generated
		 */
    EClass ROOT = eINSTANCE.getRoot();

    /**
		 * The meta object literal for the '<em><b>Model</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference ROOT__MODEL = eINSTANCE.getRoot_Model();

  }

} //XAIModelPackage
