/**
 * generated by Xtext 2.39.0
 */
package com.example.xai.xAIModel;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see com.example.xai.xAIModel.XAIModelPackage
 * @generated
 */
public interface XAIModelFactory extends EFactory
{
  /**
	 * The singleton instance of the factory.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  XAIModelFactory eINSTANCE = com.example.xai.xAIModel.impl.XAIModelFactoryImpl.init();

  /**
	 * Returns a new object of class '<em>Root</em>'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return a new object of class '<em>Root</em>'.
	 * @generated
	 */
  Root createRoot();

  /**
	 * Returns the package supported by this factory.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the package supported by this factory.
	 * @generated
	 */
  XAIModelPackage getXAIModelPackage();

} //XAIModelFactory
