/**
 * generated by Xtext 2.39.0
 */
package com.example.xai.xAIModel.impl;

import com.example.xai.model.explainableAI.explainableAIPackage;

import com.example.xai.xAIModel.Root;
import com.example.xai.xAIModel.XAIModelFactory;
import com.example.xai.xAIModel.XAIModelPackage;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class XAIModelPackageImpl extends EPackageImpl implements XAIModelPackage
{
  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  private EClass rootEClass = null;

  /**
	 * Creates an instance of the model <b>Package</b>, registered with
	 * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
	 * package URI value.
	 * <p>Note: the correct way to create the package is via the static
	 * factory method {@link #init init()}, which also performs
	 * initialization of the package, or returns the registered package,
	 * if one already exists.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.eclipse.emf.ecore.EPackage.Registry
	 * @see com.example.xai.xAIModel.XAIModelPackage#eNS_URI
	 * @see #init()
	 * @generated
	 */
  private XAIModelPackageImpl()
  {
		super(eNS_URI, XAIModelFactory.eINSTANCE);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  private static boolean isInited = false;

  /**
	 * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
	 *
	 * <p>This method is used to initialize {@link XAIModelPackage#eINSTANCE} when that field is accessed.
	 * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #eNS_URI
	 * @see #createPackageContents()
	 * @see #initializePackageContents()
	 * @generated
	 */
  public static XAIModelPackage init()
  {
		if (isInited) return (XAIModelPackage)EPackage.Registry.INSTANCE.getEPackage(XAIModelPackage.eNS_URI);

		// Obtain or create and register package
		Object registeredXAIModelPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
		XAIModelPackageImpl theXAIModelPackage = registeredXAIModelPackage instanceof XAIModelPackageImpl ? (XAIModelPackageImpl)registeredXAIModelPackage : new XAIModelPackageImpl();

		isInited = true;

		// Initialize simple dependencies
		explainableAIPackage.eINSTANCE.eClass();

		// Create package meta-data objects
		theXAIModelPackage.createPackageContents();

		// Initialize created meta-data
		theXAIModelPackage.initializePackageContents();

		// Mark meta-data to indicate it can't be changed
		theXAIModelPackage.freeze();

		// Update the registry and return the package
		EPackage.Registry.INSTANCE.put(XAIModelPackage.eNS_URI, theXAIModelPackage);
		return theXAIModelPackage;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public EClass getRoot()
  {
		return rootEClass;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public EReference getRoot_Model()
  {
		return (EReference)rootEClass.getEStructuralFeatures().get(0);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public XAIModelFactory getXAIModelFactory()
  {
		return (XAIModelFactory)getEFactoryInstance();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  private boolean isCreated = false;

  /**
	 * Creates the meta-model objects for the package.  This method is
	 * guarded to have no affect on any invocation but its first.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public void createPackageContents()
  {
		if (isCreated) return;
		isCreated = true;

		// Create classes and their features
		rootEClass = createEClass(ROOT);
		createEReference(rootEClass, ROOT__MODEL);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  private boolean isInitialized = false;

  /**
	 * Complete the initialization of the package and its meta-model.  This
	 * method is guarded to have no affect on any invocation but its first.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public void initializePackageContents()
  {
		if (isInitialized) return;
		isInitialized = true;

		// Initialize package
		setName(eNAME);
		setNsPrefix(eNS_PREFIX);
		setNsURI(eNS_URI);

		// Obtain other dependent packages
		explainableAIPackage theexplainableAIPackage = (explainableAIPackage)EPackage.Registry.INSTANCE.getEPackage(explainableAIPackage.eNS_URI);

		// Create type parameters

		// Set bounds for type parameters

		// Add supertypes to classes

		// Initialize classes and features; add operations and parameters
		initEClass(rootEClass, Root.class, "Root", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
		initEReference(getRoot_Model(), theexplainableAIPackage.getModel(), null, "model", null, 0, 1, Root.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

		// Create resource
		createResource(eNS_URI);
	}

} //XAIModelPackageImpl
