/*
 * generated by Xtext 2.39.0
 */
package com.example.xai;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XAIModelRuntimeModule extends AbstractXAIModelRuntimeModule {
}
