/*
 * generated by Xtext 2.39.0
 */
package com.example.xai;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class XAIModelStandaloneSetup extends XAIModelStandaloneSetupGenerated {

	public static void doSetup() {
		new XAIModelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
