/*
 * generated by Xtext 2.39.0
 */
package com.example.xai.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class XAIModelAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/example/xai/parser/antlr/internal/InternalXAIModel.tokens");
	}
}
