/*
 * generated by Xtext 2.39.0
 */
package com.example.xai.parser.antlr;

import com.example.xai.parser.antlr.internal.InternalXAIModelParser;
import com.example.xai.services.XAIModelGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class XAIModelParser extends AbstractAntlrParser {

	@Inject
	private XAIModelGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalXAIModelParser createParser(XtextTokenStream stream) {
		return new InternalXAIModelParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Root";
	}

	public XAIModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XAIModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
