/*
 * generated by Xtext 2.39.0
 */
package com.example.xai.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class XAIModelGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class RootElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.example.xai.XAIModel.Root");
		private final Assignment cModelAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cModelModelSpecParserRuleCall_0 = (RuleCall)cModelAssignment.eContents().get(0);
		
		//Root:
		//    model=ModelSpec
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//model=ModelSpec
		public Assignment getModelAssignment() { return cModelAssignment; }
		
		//ModelSpec
		public RuleCall getModelModelSpecParserRuleCall_0() { return cModelModelSpecParserRuleCall_0; }
	}
	public class ModelSpecElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.example.xai.XAIModel.ModelSpec");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cModelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cModelTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cModelTypeIDTerminalRuleCall_3_0 = (RuleCall)cModelTypeAssignment_3.eContents().get(0);
		private final Keyword cForKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cUserAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cUserUserSpecParserRuleCall_5_0 = (RuleCall)cUserAssignment_5.eContents().get(0);
		private final Keyword cDataKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cDatasetAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cDatasetDatasetSpecParserRuleCall_7_0 = (RuleCall)cDatasetAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cExplainKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cMethodAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cMethodIDTerminalRuleCall_8_1_0 = (RuleCall)cMethodAssignment_8_1.eContents().get(0);
		
		//ModelSpec returns xai::Model:
		//    'model' name=ID
		//    'type' modelType=ID
		//    'for' user=UserSpec
		//    'data' dataset=DatasetSpec
		//    ('explain' method=ID)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'model' name=ID
		//'type' modelType=ID
		//'for' user=UserSpec
		//'data' dataset=DatasetSpec
		//('explain' method=ID)?
		public Group getGroup() { return cGroup; }
		
		//'model'
		public Keyword getModelKeyword_0() { return cModelKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'type'
		public Keyword getTypeKeyword_2() { return cTypeKeyword_2; }
		
		//modelType=ID
		public Assignment getModelTypeAssignment_3() { return cModelTypeAssignment_3; }
		
		//ID
		public RuleCall getModelTypeIDTerminalRuleCall_3_0() { return cModelTypeIDTerminalRuleCall_3_0; }
		
		//'for'
		public Keyword getForKeyword_4() { return cForKeyword_4; }
		
		//user=UserSpec
		public Assignment getUserAssignment_5() { return cUserAssignment_5; }
		
		//UserSpec
		public RuleCall getUserUserSpecParserRuleCall_5_0() { return cUserUserSpecParserRuleCall_5_0; }
		
		//'data'
		public Keyword getDataKeyword_6() { return cDataKeyword_6; }
		
		//dataset=DatasetSpec
		public Assignment getDatasetAssignment_7() { return cDatasetAssignment_7; }
		
		//DatasetSpec
		public RuleCall getDatasetDatasetSpecParserRuleCall_7_0() { return cDatasetDatasetSpecParserRuleCall_7_0; }
		
		//('explain' method=ID)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'explain'
		public Keyword getExplainKeyword_8_0() { return cExplainKeyword_8_0; }
		
		//method=ID
		public Assignment getMethodAssignment_8_1() { return cMethodAssignment_8_1; }
		
		//ID
		public RuleCall getMethodIDTerminalRuleCall_8_1_0() { return cMethodIDTerminalRuleCall_8_1_0; }
	}
	public class UserSpecElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.example.xai.XAIModel.UserSpec");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUserKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cExpertiseKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cExpertiseAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cExpertiseIDTerminalRuleCall_4_0 = (RuleCall)cExpertiseAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cFormatKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cEqualsSignKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		private final Assignment cFormatAssignment_5_3 = (Assignment)cGroup_5.eContents().get(3);
		private final RuleCall cFormatIDTerminalRuleCall_5_3_0 = (RuleCall)cFormatAssignment_5_3.eContents().get(0);
		private final Group cGroup_5_4 = (Group)cGroup_5.eContents().get(4);
		private final Keyword cCommaKeyword_5_4_0 = (Keyword)cGroup_5_4.eContents().get(0);
		private final Assignment cFormatAssignment_5_4_1 = (Assignment)cGroup_5_4.eContents().get(1);
		private final RuleCall cFormatIDTerminalRuleCall_5_4_1_0 = (RuleCall)cFormatAssignment_5_4_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_5_5 = (Keyword)cGroup_5.eContents().get(5);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDetailsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cEqualsSignKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cDetailsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cDetailsIDTerminalRuleCall_6_2_0 = (RuleCall)cDetailsAssignment_6_2.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cPurposeKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cEqualsSignKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cPurposeAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cPurposeIDTerminalRuleCall_7_2_0 = (RuleCall)cPurposeAssignment_7_2.eContents().get(0);
		
		//UserSpec returns xai::User:
		//    'user' name=ID
		//    'expertise' '=' expertise=ID
		//    ('format' '=' '[' format+=ID (',' format+=ID)* ']')?
		//    ('details' '=' details=ID)?
		//    ('purpose' '=' purpose=ID)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'user' name=ID
		//'expertise' '=' expertise=ID
		//('format' '=' '[' format+=ID (',' format+=ID)* ']')?
		//('details' '=' details=ID)?
		//('purpose' '=' purpose=ID)?
		public Group getGroup() { return cGroup; }
		
		//'user'
		public Keyword getUserKeyword_0() { return cUserKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'expertise'
		public Keyword getExpertiseKeyword_2() { return cExpertiseKeyword_2; }
		
		//'='
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }
		
		//expertise=ID
		public Assignment getExpertiseAssignment_4() { return cExpertiseAssignment_4; }
		
		//ID
		public RuleCall getExpertiseIDTerminalRuleCall_4_0() { return cExpertiseIDTerminalRuleCall_4_0; }
		
		//('format' '=' '[' format+=ID (',' format+=ID)* ']')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'format'
		public Keyword getFormatKeyword_5_0() { return cFormatKeyword_5_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_5_1() { return cEqualsSignKeyword_5_1; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_5_2() { return cLeftSquareBracketKeyword_5_2; }
		
		//format+=ID
		public Assignment getFormatAssignment_5_3() { return cFormatAssignment_5_3; }
		
		//ID
		public RuleCall getFormatIDTerminalRuleCall_5_3_0() { return cFormatIDTerminalRuleCall_5_3_0; }
		
		//(',' format+=ID)*
		public Group getGroup_5_4() { return cGroup_5_4; }
		
		//','
		public Keyword getCommaKeyword_5_4_0() { return cCommaKeyword_5_4_0; }
		
		//format+=ID
		public Assignment getFormatAssignment_5_4_1() { return cFormatAssignment_5_4_1; }
		
		//ID
		public RuleCall getFormatIDTerminalRuleCall_5_4_1_0() { return cFormatIDTerminalRuleCall_5_4_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_5_5() { return cRightSquareBracketKeyword_5_5; }
		
		//('details' '=' details=ID)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'details'
		public Keyword getDetailsKeyword_6_0() { return cDetailsKeyword_6_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_6_1() { return cEqualsSignKeyword_6_1; }
		
		//details=ID
		public Assignment getDetailsAssignment_6_2() { return cDetailsAssignment_6_2; }
		
		//ID
		public RuleCall getDetailsIDTerminalRuleCall_6_2_0() { return cDetailsIDTerminalRuleCall_6_2_0; }
		
		//('purpose' '=' purpose=ID)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'purpose'
		public Keyword getPurposeKeyword_7_0() { return cPurposeKeyword_7_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_7_1() { return cEqualsSignKeyword_7_1; }
		
		//purpose=ID
		public Assignment getPurposeAssignment_7_2() { return cPurposeAssignment_7_2; }
		
		//ID
		public RuleCall getPurposeIDTerminalRuleCall_7_2_0() { return cPurposeIDTerminalRuleCall_7_2_0; }
	}
	public class DatasetSpecElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.example.xai.XAIModel.DatasetSpec");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDatasetKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cPathKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPathAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPathSTRINGTerminalRuleCall_3_0 = (RuleCall)cPathAssignment_3.eContents().get(0);
		private final Keyword cFormatKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cEqualsSignKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cFormatAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cFormatIDTerminalRuleCall_6_0 = (RuleCall)cFormatAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cTargetKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cEqualsSignKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cTargetColumnAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cTargetColumnSTRINGTerminalRuleCall_7_2_0 = (RuleCall)cTargetColumnAssignment_7_2.eContents().get(0);
		
		//DatasetSpec returns xai::Dataset:
		//    'dataset'
		//      'path' '=' path=STRING
		//      'format' '=' format=ID
		//      ('target' '=' targetColumn=STRING)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'dataset'
		//  'path' '=' path=STRING
		//  'format' '=' format=ID
		//  ('target' '=' targetColumn=STRING)?
		public Group getGroup() { return cGroup; }
		
		//'dataset'
		public Keyword getDatasetKeyword_0() { return cDatasetKeyword_0; }
		
		//'path'
		public Keyword getPathKeyword_1() { return cPathKeyword_1; }
		
		//'='
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//path=STRING
		public Assignment getPathAssignment_3() { return cPathAssignment_3; }
		
		//STRING
		public RuleCall getPathSTRINGTerminalRuleCall_3_0() { return cPathSTRINGTerminalRuleCall_3_0; }
		
		//'format'
		public Keyword getFormatKeyword_4() { return cFormatKeyword_4; }
		
		//'='
		public Keyword getEqualsSignKeyword_5() { return cEqualsSignKeyword_5; }
		
		//format=ID
		public Assignment getFormatAssignment_6() { return cFormatAssignment_6; }
		
		//ID
		public RuleCall getFormatIDTerminalRuleCall_6_0() { return cFormatIDTerminalRuleCall_6_0; }
		
		//('target' '=' targetColumn=STRING)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'target'
		public Keyword getTargetKeyword_7_0() { return cTargetKeyword_7_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_7_1() { return cEqualsSignKeyword_7_1; }
		
		//targetColumn=STRING
		public Assignment getTargetColumnAssignment_7_2() { return cTargetColumnAssignment_7_2; }
		
		//STRING
		public RuleCall getTargetColumnSTRINGTerminalRuleCall_7_2_0() { return cTargetColumnSTRINGTerminalRuleCall_7_2_0; }
	}
	
	
	private final RootElements pRoot;
	private final ModelSpecElements pModelSpec;
	private final UserSpecElements pUserSpec;
	private final DatasetSpecElements pDatasetSpec;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public XAIModelGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRoot = new RootElements();
		this.pModelSpec = new ModelSpecElements();
		this.pUserSpec = new UserSpecElements();
		this.pDatasetSpec = new DatasetSpecElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.example.xai.XAIModel".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Root:
	//    model=ModelSpec
	//;
	public RootElements getRootAccess() {
		return pRoot;
	}
	
	public ParserRule getRootRule() {
		return getRootAccess().getRule();
	}
	
	//ModelSpec returns xai::Model:
	//    'model' name=ID
	//    'type' modelType=ID
	//    'for' user=UserSpec
	//    'data' dataset=DatasetSpec
	//    ('explain' method=ID)?
	//;
	public ModelSpecElements getModelSpecAccess() {
		return pModelSpec;
	}
	
	public ParserRule getModelSpecRule() {
		return getModelSpecAccess().getRule();
	}
	
	//UserSpec returns xai::User:
	//    'user' name=ID
	//    'expertise' '=' expertise=ID
	//    ('format' '=' '[' format+=ID (',' format+=ID)* ']')?
	//    ('details' '=' details=ID)?
	//    ('purpose' '=' purpose=ID)?
	//;
	public UserSpecElements getUserSpecAccess() {
		return pUserSpec;
	}
	
	public ParserRule getUserSpecRule() {
		return getUserSpecAccess().getRule();
	}
	
	//DatasetSpec returns xai::Dataset:
	//    'dataset'
	//      'path' '=' path=STRING
	//      'format' '=' format=ID
	//      ('target' '=' targetColumn=STRING)?
	//;
	public DatasetSpecElements getDatasetSpecAccess() {
		return pDatasetSpec;
	}
	
	public ParserRule getDatasetSpecRule() {
		return getDatasetSpecAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
