/*
 * generated by Xtext 2.39.0
 */
package com.example.xai.ui.tests;

import com.example.xai.dsl.ui.internal.DslActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class XAIModelUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("com.example.xai.XAIModel");
	}

}
