/**
 */
package com.example.xai.model.xaiConfig.provider;

import com.example.xai.model.xaiConfig.util.XaiConfigAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class XaiConfigItemProviderAdapterFactory extends XaiConfigAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public XaiConfigItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.example.xai.model.xaiConfig.Configuration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConfigurationItemProvider configurationItemProvider;

	/**
	 * This creates an adapter for a {@link com.example.xai.model.xaiConfig.Configuration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConfigurationAdapter() {
		if (configurationItemProvider == null) {
			configurationItemProvider = new ConfigurationItemProvider(this);
		}

		return configurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.example.xai.model.xaiConfig.ExpertiseLevel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExpertiseLevelItemProvider expertiseLevelItemProvider;

	/**
	 * This creates an adapter for a {@link com.example.xai.model.xaiConfig.ExpertiseLevel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExpertiseLevelAdapter() {
		if (expertiseLevelItemProvider == null) {
			expertiseLevelItemProvider = new ExpertiseLevelItemProvider(this);
		}

		return expertiseLevelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.example.xai.model.xaiConfig.DetailsLevel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DetailsLevelItemProvider detailsLevelItemProvider;

	/**
	 * This creates an adapter for a {@link com.example.xai.model.xaiConfig.DetailsLevel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDetailsLevelAdapter() {
		if (detailsLevelItemProvider == null) {
			detailsLevelItemProvider = new DetailsLevelItemProvider(this);
		}

		return detailsLevelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.example.xai.model.xaiConfig.OutputFormat} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OutputFormatItemProvider outputFormatItemProvider;

	/**
	 * This creates an adapter for a {@link com.example.xai.model.xaiConfig.OutputFormat}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOutputFormatAdapter() {
		if (outputFormatItemProvider == null) {
			outputFormatItemProvider = new OutputFormatItemProvider(this);
		}

		return outputFormatItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.example.xai.model.xaiConfig.Purpose} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PurposeItemProvider purposeItemProvider;

	/**
	 * This creates an adapter for a {@link com.example.xai.model.xaiConfig.Purpose}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPurposeAdapter() {
		if (purposeItemProvider == null) {
			purposeItemProvider = new PurposeItemProvider(this);
		}

		return purposeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.example.xai.model.xaiConfig.DebugTechnique} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DebugTechniqueItemProvider debugTechniqueItemProvider;

	/**
	 * This creates an adapter for a {@link com.example.xai.model.xaiConfig.DebugTechnique}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDebugTechniqueAdapter() {
		if (debugTechniqueItemProvider == null) {
			debugTechniqueItemProvider = new DebugTechniqueItemProvider(this);
		}

		return debugTechniqueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.example.xai.model.xaiConfig.DatasetType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatasetTypeItemProvider datasetTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.example.xai.model.xaiConfig.DatasetType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatasetTypeAdapter() {
		if (datasetTypeItemProvider == null) {
			datasetTypeItemProvider = new DatasetTypeItemProvider(this);
		}

		return datasetTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.example.xai.model.xaiConfig.TrainingPolicy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TrainingPolicyItemProvider trainingPolicyItemProvider;

	/**
	 * This creates an adapter for a {@link com.example.xai.model.xaiConfig.TrainingPolicy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTrainingPolicyAdapter() {
		if (trainingPolicyItemProvider == null) {
			trainingPolicyItemProvider = new TrainingPolicyItemProvider(this);
		}

		return trainingPolicyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.example.xai.model.xaiConfig.AIModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AIModelItemProvider aiModelItemProvider;

	/**
	 * This creates an adapter for a {@link com.example.xai.model.xaiConfig.AIModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAIModelAdapter() {
		if (aiModelItemProvider == null) {
			aiModelItemProvider = new AIModelItemProvider(this);
		}

		return aiModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.example.xai.model.xaiConfig.Parameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParameterItemProvider parameterItemProvider;

	/**
	 * This creates an adapter for a {@link com.example.xai.model.xaiConfig.Parameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParameterAdapter() {
		if (parameterItemProvider == null) {
			parameterItemProvider = new ParameterItemProvider(this);
		}

		return parameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.example.xai.model.xaiConfig.ExplanationMethod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExplanationMethodItemProvider explanationMethodItemProvider;

	/**
	 * This creates an adapter for a {@link com.example.xai.model.xaiConfig.ExplanationMethod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExplanationMethodAdapter() {
		if (explanationMethodItemProvider == null) {
			explanationMethodItemProvider = new ExplanationMethodItemProvider(this);
		}

		return explanationMethodItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (configurationItemProvider != null) configurationItemProvider.dispose();
		if (expertiseLevelItemProvider != null) expertiseLevelItemProvider.dispose();
		if (detailsLevelItemProvider != null) detailsLevelItemProvider.dispose();
		if (outputFormatItemProvider != null) outputFormatItemProvider.dispose();
		if (purposeItemProvider != null) purposeItemProvider.dispose();
		if (debugTechniqueItemProvider != null) debugTechniqueItemProvider.dispose();
		if (datasetTypeItemProvider != null) datasetTypeItemProvider.dispose();
		if (trainingPolicyItemProvider != null) trainingPolicyItemProvider.dispose();
		if (aiModelItemProvider != null) aiModelItemProvider.dispose();
		if (parameterItemProvider != null) parameterItemProvider.dispose();
		if (explanationMethodItemProvider != null) explanationMethodItemProvider.dispose();
	}

}
